# Parameters for MST python code
# Imène Goumiri
# October 16, 2016

# beta_0 = beta_theta * B_theta(r=1)^2 / (2 ∫ r⋅P(r) dr)
beta_theta = 0.07

# Mock parameters
mu0 = 0.000001256637061 # pi * 4e-7
aspect_ratio = 3.0 # aspect ratio
a = 0.5 # minor radius, also same as minor_b for MST
zneo = 1.5 # trapped electron enhancement
zeff = 2.6 # used to match an MST data set

# Simulation mode
mode = "STD_400KA_realdata"
# mode = "imene"
# mode = "OFCD_400_CC"

save = "output_{0}.dat"

[pressure]
	# p(r) = p(0) * (1 - r^c1)^c2
	c1 = 3.561552813 # c1 = (3 + sqrt(17)) / 2
	c2 = 2.0

[rho]
	min = 0.0
	max = 1.0
	ndiv = 50 # => step = 0.02

[time]
	t0 = 6.700009107589721680e-4 # 0.0 # 0.00321 # 0.0
	tf = 0.1 # 0.041010
	dt = 1.0e-5
	# ndiv = 10_000

[alpha]
	min = 3.99
	max = 4.01
	ndiv = 4

[lambda_0]
	min = 0.0
	max = 4.0
	ndiv = 400 # => step = 0.01
	# ndiv = 40 # => step = 0.1

[initial]
	I_phi = 100.0
	# I_phi = 1.253e5 # -32.99 # 2.4111e5


[control]
	A = [
		[ 0.9965, 0.0, 0.0, 0.0, 0.0 ],
		[ 0.0, 0.78343286, 0.0, 0.0, 0.0 ],
		[ 0.0, 0.0, 0.71399286, 0.0, 0.0 ],
		[ 0.0, 0.0, 0.0, 0.45264107, 0.0 ],
		[ 0.0, 0.0, 0.0, 0.0, 1.0 ],
	]
	B = [
		[ 1.31194e-6, 1.6094487e-5 ],
		[ 0.00824369, 0.019284863 ],
		[ 0.00517165, 0.0094343913 ],
		[ 0.00180773, 0.0030333268 ],
		[ 0.0, -1.0e-5 ],
	]
	C = [
		[ 23.5314, 0.11821832, -0.30220567, 0.3153685, 0.0 ],
		[ 0.0, 0.0, 0.0, 0.0, 1.0 ],
	]
	D = [
		[ 0.0, 0.0 ],
		[ 0.0, 0.0 ],
	]
	F = [
		[ 640.41, 23641.499 ],
		[ 530.576, -14100.91 ],
	]
	K = [
		[ 12391.6, -0.57841858, 4.4208818, -1.4621009, 23641.499 ],
		[ 12334.0, 46.45135, -103.49108, 60.767871, -14100.91 ],
	]
	Ki = [
		[ -0.0636136, -0.074770252 ],
		[ -0.0527035, 0.044596607 ],
	]
	L = [
		[ 0.0424864, 4.0589133e-17 ],
		[ 0.000121186, 1.3699285e-15 ],
		[ -0.000321088, -1.8396398e-15 ],
		[ 0.000393046, -5.3049666e-15 ],
		[ -2.65438e-24, 1.0 ],
	]
	xd = [
		[ 0.127527 ],
		[ -0.434042 ],
		[ -0.206184 ],
		[ -0.0376587 ],
		[ 0.04 ],
	]
	ud = [
		[ -17.2718 ],
		[ 0.0 ],
	]
	r1 = [
		[ 3.0 ],
		[ 0.04 ],
	]
	r2 = [
		[ 2.5 ],
		[ 0.05 ],
	]
	r0 = [
		[ 3.10144 ],
		[ 0.0408002 ],
	]
	u0 = [
		[ -5.86927 ],
		[ 0.0 ],
	]

	Theta1 = 1.35
	Theta2 = 0.96
	F1 = 0.11
	F2 = 0.55
	Ip1 = 169.0e3
	Ip2 = 147.0e3

	t1 = 0.025
	t2 = 0.040
	dt = 1.0e-5

[imene]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 3.0
	density_ref = 1.0e19 # 1.0e19 # reference plasma density
	density_multiplier = 1.0
# [imene.density]
# 	time = { file = "density.dat", column = 1 }
# 	value = { file = "density.dat", column = 2 }
[imene.toroidal] # phi
	time = { file = "voltages.dat", column = 1 }
	voltage = { file = "voltages.dat", column = 2 }
	DC_voltage = 0.0
[imene.poloidal] # theta
	time = { file = "voltages.dat", column = 1 }
	voltage = { file = "voltages.dat", column = 3 }
[imene.anomalous] # anom
	time = [0.00321, 0.012, 0.1]
	voltage = [1.0, 1.0, 1.0]


[STD_400KA_realdata]
	# shot = 1141218048
	shot = 1100903060
	time = { file = "realdata.dat", column = 1 }
	P_ohm_over_I_phi = { file = "realdata.dat", column = 8 }
	theta = { file = "realdata.dat", column = 9 }
	f = { file = "realdata.dat", column = 10 }
	density_ref = 8.0e18
	density_multiplier = 1
[STD_400KA_realdata.alpha]
	time = { file = "realdata.dat", column = 1 }
	value = { file = "realdata.dat", column = 2 }
[STD_400KA_realdata.flux]
	ref = 0.0306 # reference toroidal flux, in Wb
	# multiplier = 0.467503662495
	multiplier = 0.880962371631
	time = { file = "realdata.dat", column = 1 }
	value = { file = "realdata.dat", column = 5 }
# [STD_400KA_realdata.density]
# 	time = { file = "density.dat", column = 1 }
# 	value = { file = "density.dat", column = 2 }
[STD_400KA_realdata.toroidal] # phi
	time = { file = "realdata.dat", column = 1 }
	current = { file = "realdata.dat", column = 7 }
	voltage = { file = "realdata.dat", column = 3 }
	DC_voltage = 0.0
[STD_400KA_realdata.poloidal] # theta
	time = { file = "realdata.dat", column = 1 }
	current = { file = "realdata.dat", column = 6 }
	voltage = { file = "realdata.dat", column = 4 }
[STD_400KA_realdata.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]


[STD_400KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 1.0
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[STD_400KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.032, 0.037, 0.085, 1.0]
	voltage = [180.0, 37.0, 27.0, 9.0, 25.0, -4.0, 0.0, 0.0]
	DC_voltage = 0.0
[STD_400KA.poloidal] # theta
	time = [0.0, 0.012, 0.032, 0.04, 0.06, 0.07, 0.077, 0.08, 1.0]
	# voltage = [-7.0, -0.5, -0.3, 1.2, 1.7, 2.0, 5.5, 0.0, 0.0]
	voltage = [-4.0, 1.5, 1.3, 5.2, 11.7, 3.0, -5.5, -1.0, 0.0]
[STD_400KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]


[BTPPS]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 1.0
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[BTPPS.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.032, 0.037, 0.085, 1.0]
	# voltage = [180.0, 37.0, 27.0, 9.0, 25.0, -4.0, 0.0, 0.0]
	voltage = [90.0, 18.5, 13.5, 4.5, 12.5, -2.0, 0.0, 0.0]
	# voltage = [135.0, 27.75, 20.25, 6.75, 18.75, -3.0, 0.0, 0.0]
	DC_voltage = 0.0
[BTPPS.poloidal] # theta
	time = [0.0, 0.012, 0.032, 0.04, 0.06, 0.07, 0.077, 0.08, 1.0]
	voltage = [-7.0, -0.5, -0.3, 1.2, 1.7, 2.0, 5.5, 0.0, 0.0]
[BTPPS.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]


[MM_550KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 3.47
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[MM_550KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.032, 0.037, 0.085, 1.0]
	voltage = [148.0, 37.0, 11.7, 11.7, 11.7, -5.0, 0.0, 0.0]
	DC_voltage = 0.0
[MM_550KA.poloidal] # theta
	time = [0.0, 0.012, 0.03, 0.04, 0.065, 0.085, 0.09, 1.0]
	voltage = [0.0, 0.0, 0.0, 1.55, 1.55, 2.2, 0.0, 0.0]
[MM_550KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]


[MM_MAX_IP]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 6.5
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 3.0
[MM_MAX_IP.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.032, 0.037, 0.1, 1.0]
	voltage = [246.5, 43.0, 11.5, 11.5, 11.5, -20.0, 0.0, 0.0]
	DC_voltage = 0.0
[MM_MAX_IP.poloidal] # theta
	time = [0.0, 0.012, 0.032, 0.04, 0.065, 0.085, 0.09, 1.0]
	voltage = [0.0, 0.0, 0.0, 2.9, 2.9, 3.19, 0.0, 0.0]
[MM_MAX_IP.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]


[MOCK_400KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 1.15
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[MOCK_400KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.05, 0.055, 0.085, 1.0]
	voltage = [148.0, 40.0, 16.3, 16.3, 16.3, -5.0, -5.0, 0.0]
	DC_voltage = 0.0
[MOCK_400KA.poloidal] # theta
	time = [0.0, 0.01, 0.05, 0.055, 0.06, 0.07, 0.08, 0.085, 1.0]
	voltage = [-7.5, 0.0, 0.0, 1.6, 1.6, 1.6, 1.6, 0.0, 0.0]
[MOCK_400KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]


[OPCD_400KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 1.15
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[OPCD_400KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.05, 0.055, 0.085, 1.0]
	voltage = [148.0, 40.0, 16.3, 16.3, 16.3, -5.0, -5.0, 0.0]
	DC_voltage = 0.0
[OPCD_400KA.poloidal] # theta
	time = [0.0, 0.01, 0.05, 0.055, 0.06, 0.07, 0.08, 0.085, 1.0]
	voltage = [-7.5, 0.0, 0.0, 1.6, 1.6, 1.6, 1.6, 0.0, 0.0]
[OPCD_400KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]
[OPCD_400KA.OPCD]
	t_start = 0.015
	cycles = 12.0
	freq = 250.0
	max_voltage = 25.0


[OFCD_400KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 1.15
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[OFCD_400KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.05, 0.055, 0.085, 1.0]
	voltage = [148.0, 40.0, 16.3, 16.3, 16.3, -5.0, -5.0, 0.0]
	DC_voltage = 0.0
[OFCD_400KA.poloidal] # theta
	time = [0.0, 0.01, 0.05, 0.055, 0.06, 0.07, 0.08, 0.085, 1.0]
	voltage = [-7.5, 0.0, 0.0, 1.6, 1.6, 1.6, 1.6, 0.0, 0.0]
[OFCD_400KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]
[OFCD_400KA.OFCD]
	t_start = 0.015
	cycles = 12.0
	freq = 250.0
	phase = 0.25
	max_voltage = 20.0


[OFCD_400_CC]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 1.15
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[OFCD_400_CC.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.05, 0.055, 0.085, 1.0]
	voltage = [148.0, 40.0, 16.3, 16.3, 16.3, -5.0, -5.0, 0.0]
	DC_voltage = 0.0
[OFCD_400_CC.poloidal] # theta
	time = [0.0, 0.01, 0.05, 0.055, 0.06, 0.07, 0.08, 0.085, 1.0]
	voltage = [-7.5, 0.0, 0.0, 1.6, 1.6, 1.6, 1.6, 0.0, 0.0]
[OFCD_400_CC.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]
[OFCD_400_CC.OFCD]
	t_start = 0.015
	cycles = 12.0
	freq = 250.0
	phase = 0.25
	max_voltage = 20.0
[OFCD_400_CC.buck]
	time = [0.0, 0.015, 0.02, 0.06, 0.065, 1.0]
	voltage = [0.0, 0.0, -8.0, -8.0, 0.0, 0.0]


[PPCD_550KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 3.47
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[PPCD_550KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.032, 0.037, 0.085, 1.0]
	voltage = [148.0, 37.0, 11.7, 11.7, 11.7, -5.0, 0.0, 0.0]
	DC_voltage = 0.0
[PPCD_550KA.poloidal] # theta
	time = [0.0, 0.012, 0.03, 0.04, 0.065, 0.085, 0.09, 1.0]
	voltage = [0.0, 0.0, 0.0, 1.55, 1.55, 2.2, 0.0, 0.0]
[PPCD_550KA.poloidal.add] # theta
	time = [0.0, 0.03, 0.031, 0.04, 0.065, 1.0]
	voltage = [0.0, 0.0, -2.0, -2.0, 0.0, 0.0]
[PPCD_550KA.PPCD.poloidal] # theta
	time = [0.0, 0.015, 0.016, 0.03, 0.031, 1.0]
	voltage = [0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[PPCD_550KA.PPCD.Te]
	time = [0.0, 0.015, 0.016, 0.02, 0.023, 0.03, 0.031, 1.0]
	voltage = [0.0, 0.0, 0.0, 2.5333333333, 2.8, 3.0, 0.0, 0.0]
[PPCD_550KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]


[OFCD_250KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 0.732
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
	flux_0 = 0.0373 # FIXME: handle this
[OFCD_250KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.75, 0.755, 0.785, 1.0]
	voltage = [130.0, 35.0, 16.9, 16.9, 16.9, -5.0, -5.0, 0.0]
	DC_voltage = 0.0
[OFCD_250KA.poloidal] # theta
	time = [0.0, 0.01, 0.05, 0.755, 0.76, 0.77, 0.78, 0.785, 1.0]
	voltage = [-4.8, 0.0, 0.0, 0.0, 0.9, 1.02, 1.02, 0.0, 0.0]
[OFCD_250KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]
[OFCD_250KA.OFCD]
	t_start = 0.015
	cycles = 180.0
	freq = 280.0
	phase = 0.1
	max_voltage = 11.0
	offset = 0.0


[RAMP_550KA]
	flux_ref = 0.0306 # reference toroidal flux, in Wb
	flux_multiplier = 0.2
	density_ref = 1.0e19 # reference plasma density
	density_multiplier = 1.0
[RAMP_550KA.toroidal] # phi
	time = [0.0, 0.010, 0.017, 0.023, 0.032, 0.037, 0.085, 1.0]
	voltage = [148.0, 37.0, 11.7, 11.7, 11.7, -5.0, 0.0, 0.0]
	DC_voltage = 0.0
[RAMP_550KA.poloidal] # theta
	time = [0.0, 0.012, 0.03, 0.04, 0.065, 0.085, 0.09, 1.0]
	voltage = [-6.0, 0.3, 0.0, 1.55, 1.55, 2.2, 0.0, 0.0]
[RAMP_550KA.anomalous] # anom
	time = [0.0, 0.012, 1.0]
	voltage = [3.0, 1.0, 1.0]

